"use client";

/**
 * ReportView — SPEC §9.8 / §18.
 *
 * Before generation: a preview card listing the eight sections, the current
 * filter scope, and a Generate button. During: a skeleton with progress copy.
 * After: the rendered report with business name, date range, generation
 * timestamp, and a Regenerate button.
 *
 * Markdown is rendered through react-markdown with raw HTML disabled (§22.6).
 *
 * "Download as Markdown" and the print stylesheet are P1 (§32) and follow once
 * every P0 item is complete and deployed.
 */

import Markdown from "react-markdown";
import { Button } from "@/components/ui/Button";
import { Card, CardTitle } from "@/components/ui/Card";
import { Skeleton } from "@/components/ui/Skeleton";
import { REPORT_SECTIONS } from "@/lib/ai/uiCopy";
import { useAIReport } from "@/hooks/useAIReport";
import { formatDateLong, formatRange } from "@/lib/utils/format";
import type { Dataset } from "@/types/dataset";
import type { DateWindow } from "@/types/analytics";
import type { Filters } from "@/context/FilterContext";

const DISCLAIMER =
  "This report is generated by an AI model from your data. Observations are computed from your records; recommendations are suggestions, not financial advice.";

/** Used when no model was involved — claiming AI authorship would be false. */
const COMPUTED_DISCLAIMER =
  "This report was computed directly from your data in your browser; no AI model was involved. Observations are calculated from your records; recommendations are suggestions, not financial advice.";

function scopeLine(window: DateWindow, filters: Filters): string {
  const categories =
    filters.categories === "all"
      ? "All categories"
      : filters.categories.length === 1
        ? filters.categories[0]
        : `${filters.categories.length} categories`;
  return `${formatRange(window.start, window.end)} · ${categories}`;
}

export function ReportView({
  dataset,
  window,
  filters,
}: {
  dataset: Dataset;
  window: DateWindow;
  filters: Filters;
}) {
  const { status, markdown, error, generatedAt, generate, source, aiAvailable } = useAIReport();
  const scope = scopeLine(window, filters);

  return (
    <div className="mx-auto flex w-full max-w-chat flex-col gap-5 p-4 md:p-6">
      <div>
        <h1 className="text-h1 text-text-900">AI Business Report</h1>
        <p className="text-small text-text-600">
          An eight-section written report, generated from the figures currently on your dashboard.
        </p>
      </div>

      {!aiAvailable && (
        <div
          role="status"
          className="rounded-lg border border-warning/30 bg-[#FFFBEB] px-4 py-3 text-small text-text-600"
        >
          <strong className="font-medium text-text-900">Offline report mode.</strong> This
          deployment has no AI API key configured, so the report below is{" "}
          <strong className="font-medium text-text-900">computed directly from your data</strong>{" "}
          rather than written by a language model. It follows the same eight sections and cites the
          same figures. Add an <code>ANTHROPIC_API_KEY</code> to enable the written version.
        </div>
      )}

      {/* ── Before generation: preview card (§9.8) ── */}
      {status === "idle" && (
        <Card className="flex flex-col gap-4">
          <div>
            <CardTitle>What this report will cover</CardTitle>
            <p className="mt-1 text-small text-text-600">
              Scope: <span className="text-text-900">{scope}</span>
            </p>
          </div>
          <ol className="grid gap-1.5 sm:grid-cols-2">
            {REPORT_SECTIONS.map((section, i) => (
              <li key={section} className="flex items-baseline gap-2 text-small text-text-600">
                <span className="nums text-text-400">{i + 1}.</span>
                {section}
              </li>
            ))}
          </ol>
          <div>
            <Button onClick={generate}>
              {aiAvailable ? "Generate report" : "Generate computed report"}
            </Button>
          </div>
        </Card>
      )}

      {/* ── During: skeleton with progress copy (§9.8) ── */}
      {status === "generating" && (
        <Card className="flex flex-col gap-4">
          <p className="text-small text-text-600" aria-live="polite">
            Writing your report from {scope.toLowerCase()}… this usually takes a few seconds.
          </p>
          {markdown.length === 0 ? (
            <div className="flex flex-col gap-3">
              <Skeleton className="h-5 w-1/3" />
              <Skeleton className="h-3 w-full" />
              <Skeleton className="h-3 w-11/12" />
              <Skeleton className="h-3 w-4/5" />
              <Skeleton className="mt-3 h-5 w-1/4" />
              <Skeleton className="h-3 w-full" />
              <Skeleton className="h-3 w-3/4" />
            </div>
          ) : (
            <ReportMarkdown markdown={markdown} />
          )}
        </Card>
      )}

      {/* ── Error (§24) ── */}
      {status === "error" && (
        <div
          role="alert"
          className="flex flex-wrap items-center gap-3 rounded-lg border border-error/30 bg-[#FEF2F2] px-4 py-3 text-small text-error"
        >
          <span className="flex-1">{error}</span>
          <Button variant="secondary" size="sm" onClick={generate}>
            Retry
          </Button>
        </div>
      )}

      {/* ── After: rendered report (§9.8) ── */}
      {status === "done" && (
        <Card className="flex flex-col gap-4">
          <div className="flex flex-wrap items-start justify-between gap-3 border-b border-border pb-4">
            <div>
              <CardTitle>{dataset.name}</CardTitle>
              <p className="mt-0.5 text-small text-text-600">Period: {scope}</p>
              {source === "computed" && (
                <p className="mt-1 flex items-center gap-1.5 text-caption font-medium text-text-400">
                  <span aria-hidden="true">🧮</span> Computed from your data — not AI-generated
                </p>
              )}
              {generatedAt && (
                <p className="text-caption text-text-400">
                  Generated {formatDateLong(generatedAt)} at{" "}
                  {generatedAt.toLocaleTimeString("en-PK", {
                    hour: "2-digit",
                    minute: "2-digit",
                  })}
                </p>
              )}
            </div>
            <Button variant="secondary" size="sm" onClick={generate}>
              Regenerate
            </Button>
          </div>

          <ReportMarkdown markdown={markdown} />

          <p className="border-t border-border pt-4 text-caption text-text-400">
            {source === "computed" ? COMPUTED_DISCLAIMER : DISCLAIMER}
          </p>
        </Card>
      )}
    </div>
  );
}

function ReportMarkdown({ markdown }: { markdown: string }) {
  return (
    <div
      className={[
        "text-body text-text-600",
        "[&_h2]:mb-2 [&_h2]:mt-6 [&_h2]:text-h2 [&_h2]:text-text-900 first:[&_h2]:mt-0",
        "[&_h3]:mb-1 [&_h3]:mt-4 [&_h3]:text-h3 [&_h3]:text-text-900",
        "[&_strong]:font-medium [&_strong]:text-text-900",
        "[&_em]:not-italic [&_em]:font-medium [&_em]:text-text-900",
        "[&_p]:my-2",
        "[&_ul]:my-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ol]:my-2 [&_ol]:list-decimal [&_ol]:pl-5",
        "[&_li]:my-1",
        "[&_table]:my-3 [&_table]:w-full [&_th]:border-b [&_th]:border-border [&_th]:py-1 [&_th]:text-left",
        "[&_td]:border-b [&_td]:border-border [&_td]:py-1",
      ].join(" ")}
    >
      <Markdown>{markdown}</Markdown>
    </div>
  );
}
